services:
  tello_drone:
    image: tello_ros2:latest
    container_name: tello_drone
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp
      - QT_QPA_PLATFORM=xcb
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true
    tty: true
    command: ros2 launch tello_control tello_launch.py
